### ISSUE TITLE
Mount with specific owner

### ISSUE THREAD

**Issue by BigmenPixel0** [systemd/zram-generator#150]
Can I mount /var/cache/my_folder with specific `uid` and `gid`?
```
[zram5]
zram-size = ram
compression-algorithm = zstd
options = nosuid,nodev
fs-type = ext4
mount-point = /var/cache/my_folder
```

**Comment by nabijaczleweli** [comment]
The hack described in the README https://github.com/systemd/zram-generator#mount-points applies, just do `chown` instead of/in addition to chmod (I think that's what you're asking, per analogiam w/tmpfs).

Closing as duplicate of #146. I should really polish the half of a systemd patch I have for this.
