### ISSUE TITLE
System stuck on boot after enabling zram-generator

### ISSUE THREAD

**Issue by bertez** [systemd/zram-generator#155]
Hello, I enabled zram using zram-generator on a new arch install and the boot process is stuck on:

"A start job is running for Create swap on /dev/zram0 (_elapsed time_ / no limit)"

Failed boot log: https://gist.github.com/bertez/1e37b988b72f30e87de70aa1f563c555
Successful boot log: https://gist.github.com/bertez/5d53cb2d4c1a4ffb9c6b054a52654610
Zram Configuration: https://gist.github.com/bertez/537e0d210b0de948ddf04656ea07a378

Notes:
- It boots up occasionally, but 9 times out of 10, it does not.
- This happened after I replaced my old msata ssd with a nvme ssd, which may or may not be relevant.
- Everything works well without zram.
- I tested another operating system (Fedora) and it boots up correctly every time and also uses zram.

Thanks!

**Comment by nabijaczleweli** [comment]
uninstall udisks2
```
May 22 12:25:10 t480 systemd[1]: Found device /dev/zram0.
May 22 12:25:10 t480 systemd[1]: Created slice Slice /system/udisks2-zram-setup.
```

**Comment by bertez** [comment]
Thanks for your quick reply... so, I understand zram-generator is not compatible with udisks

udisks provides some core functionality to the file manager of many desktop environments... is this the only option?

**Comment by nabijaczleweli** [comment]
Well, so long as udisks2 doesn't trample on our zram device handling (in this case that'd be primarily the creation itself + `dev-zramX.swap` unit writing) it should be fine, but if both of them try to generate the *same* unit, then that'd be fine.

By way of test, try making that section `[zram10]` or something (and removing `writeback_device =`, since you have it pointed at the `tarta-zoot/swap-writeback` zvol which, considering you probably don't designate your pools/hosts in polish and compatibly with my machines, is probably wrong) – unless udisks2 is *very* greedy, it should Just Work.
Likewise if you disable zram handling in udisks2 config (don't use, didn't look, should™ be possible).

**Comment by bertez** [comment]
Thank you very much for your detailed response... I will definitely try that

**Comment by bertez** [comment]
About the `writeback_device =` line... yes :D ... I've copied the sample configuration file provided by the package and I've already commented that line without success...
