### ISSUE TITLE
`make install` fails on Debian

### ISSUE THREAD

**Issue by pdewacht** [systemd/zram-generator#40]
I was inspired to try zram-generator after it was mentioned in [LWN](https://lwn.net/SubscriberLink/824620/f3c3b8f9ef9fd704/). But I ran into some problems when installing it:

- `make install` installed to `/usr/lib/systemd/system-generator`, but systemd on Debian does not search that directory

- I could override the installation location by setting the `SYSTEMD_DIR` makefile variable, but `swap-create@.service` still hardcoded the wrong location and I had to edit that file by hand.

A possible fix is to change the default `SYSTEMD_DIR` to `/usr/local/lib/systemd/`. That should work on all systems, if I read the systemd docs correctly.

Alternatively the  system directory could be extracted from pkg-config (something like `pkg-config systemd --variable systemdsystemgeneratordir`?)

**Comment by pdewacht** [comment]
Also, `src/main.rs` hardcodes `/usr/lib/systemd/systemd-makefs`, which is also not correct on Debian.

**Comment by nabijaczleweli** [comment]
Which is why I mass-replace `/usr/lib/systemd` with `/lib/systemd` in my Debian package: https://github.com/nabijaczleweli/systemd-zram-generator.deb/blob/a9e5600442908e110e7f8668d9a13ffa5dad2387/debian/rules#L12. Chalk it up as a distro-specific patch v0v

Merged-usr is the default on new Debian installs, and merged-usr systems are not affected for obvious reasons. Cargo doesn't really support setting arbitrary strings at build time (which is to say you *could* do it, but it's more trouble than is worth IMO).
