### ISSUE TITLE
RFE: support non-swap zram devices

### ISSUE THREAD

**Issue by rathann** [systemd/zram-generator#46]
I would like to have an easy mechanism for creating zram devices for mounting at arbitrary locations (e.g. /var/lib/mock) persistent across reboots.

@keszybz suggested filing an RFE here.

**Comment by foundObjects** [comment]
I'll jump on board this RFE -- I'd like an easy way to create a compressed device to hold /tmp

**Comment by rathann** [comment]
Any progress here? I've been struggling to do this using regular systemd units.
I tried using the following unit to create /dev/zram1 containing ext2, but it's failing.
```
[Unit]
Description=Create ext2 on /dev/zram1
DefaultDependencies=false
ConditionPathExists=!/dev/zram1

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStartPre=zramctl --find
ExecStart=zramctl /dev/zram1 -s 12G
ExecStart=mkfs.ext2 -q /dev/zram1
ExecStop=zramctl -r /dev/zram1 
```

**Comment by polarathene** [comment]
@rathann you might be interested in [zramdrive](https://github.com/StuartIanNaylor/zramdrive). It uses OverlayFS to bind mount a location to be used in zram. (Note, that project [appears to be moved to a larger one that's actively maintained](https://github.com/ecdye/zram-config))

You could alternatively consider [F2FS for a filesystem which supports zstd transparent compression](https://www.phoronix.com/scan.php?page=news_item&px=F2FS-Zstd-Linux-5.7-Pull) (since kernel 5.7) as a feature?

**Comment by rathann** [comment]
@polarathene Thanks for the tips. zram-config does look like what I need. F2FS is still disk-based, so not ideal for my use case (larger throw-away storage for fast mock builds). Btrfs, which is the default for Fedora 33+, supports transparent compression, too.

**Comment by keszybz** [comment]
What file system would you put this? What should the default be if not specified? (I wanted to be smart and wrote some code to look up the file system on / and use that, but then I realized that you probably want something simple, like ext2).

**Comment by rathann** [comment]
I'm using ext2 right now, only because it doesn't support journalling. If you have a faster alternative, I'm all ears.

**Comment by keszybz** [comment]
Please see if #55 works for you.
