### ISSUE TITLE
RFE: support boosting zram-fraction on low memory machines

### ISSUE THREAD

**Issue by jwrdegoede** [systemd/zram-generator#51]
Hi,

As you may know I've done (and still do) a lot of work to make sure that Linux and specifically Fedora works well on Intel Bay Trail based tablets and 2-in-1s.

Some of these come with only 1G of RAM, having ZRAM enabled by default is great for these, but the fraction of 0.5 is too low. Too be able to install the Fedora 33 workstation livecd on one of these devices I need to swapoff, reconfigure zram0 to be 1G (so fraction is 1.0) and then mkswap + swapon again. Otherwise anaconda won't run.

I realize that using fraction 1.0 (or more) is a bit controversial, but generally speaking the zram compression is equal to or better then 1:3, so this takes about 1/3th of the RAM leaving the rest for normal usage.

I've been considering doing a Fedora Workstation "light" spin for these devices where changing the zram fraction would be one of the tweaks, but it would be better if we can just make things work with the main Fedora Workstation release.

As such I was wondering if it would be possible to do something for these devices, maybe add support for something like this to the config file:

```
# Settings for machines with a low amount of RAM. Machines with less RAM then the low-memory-limit
# will use the optional zram-fraction-low-mem setting as zram-fraction. This allows using a higher
# zram-fraction on low memory machines, which need all the extra (z)RAM they can get.
# The default value for both is 0, which disables this feature.
low-memory-limit = 1536
zram-fraction-low-mem = 1.0
```

Note if this is considered something which you would be willing to add when contributed, please also let me know then I will try to add this (I have 0 experience coding in rust though...).

**Comment by keszybz** [comment]
Shouldn't we just bump the fraction to 1.0?

Rationale: let's say we bump the fraction to 1.0 for low-memory devices on the assumption that compression will be effective and we'll not end up with using all physical memory. Experience so far shows that this is a fair assumption. But if that assumption holds for low-memory devices, it is even more likely to be satisfied for devices with a larger amount of memory, just because there's more stuff to compress so there's a higher chance that there'll be something compressible on the way. We probably don't want to create a too huge device, because that'd mean that a device with a huge amount of memory we'd be trading too much cpu for memory, but we're limiting the total device size, so this is not an issue. Ergo, I'd just bump it to 1.0.

**Comment by jwrdegoede** [comment]
Just bumping the fraction to 1.0, either the generator-default or in the Fedora config file, would be fine with me. I suggested the "zram-fraction-low-mem" thing because I thought that just outright bumping to 1.0 would be controversial, but if we can make that happen then that would be great.

**Comment by keszybz** [comment]
@jwrdegoede See https://fedoraproject.org/wiki/Changes/Scale_ZRAM_to_full_memory_size. I put your name on it too, I hope that's all right.

**Comment by jwrdegoede** [comment]
The change proposal looks good, thank you for doing this. And I'm fine with my name being there too.
