### ISSUE TITLE
RFE: Include Cargo.lock in sources

### ISSUE THREAD

**Issue by AdrianVovk** [systemd/zram-generator#65]
Hello!

Would you be able to start shipping a Cargo.lock file in the sources? [The rust documentation suggests that Cargo.lock should be committed for binaries](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html)

Background:
I'm trying to build this package with [BuildStream](https://buildstream.build/), which allows reproducible builds and many other benefits. There's a pretty severe limitation that network access is not allowed to make sure nothing external can muck up the build environment. Sources are first downloaded locally, then assembled into a build environment, and then compilation can occur. Cargo, of course, complicates this, since it downloads dependencies from the network during the build. The solution BuildStream came up with is to have a special kind of source that finds a Cargo.lock file in the previous sources, and then downloads the exact versions of the rust libraries to the local cache, and then puts them in the right spot for Cargo to pick them up and skip the network at build time. Without the Cargo.lock file, it is nearly impossible for me to compile this

Thank you

**Comment by keszybz** [comment]
Sorry, but the advice in https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html simply bad. The problem it is solving is specifying dependencies as "use the latest commit on the `master` branch". Specifying dependencies like that is a really stupid thing to do, and obviously things will break all the time. If a project still decides to do that, `Cargo.lock` could be considered a solution. But it is still an ugly solution to a self-inflicted problem. The real solution is to go in the *opposite* direction: specify dependencies through semantic versions, taking advantage of the compatibility promises made by projects using semantic versioning. And that is what *this* project is doing. The expectation is that compilation will work with any compatible version.

If we were to commit `Cargo.lock` to version control, two undesirable things would happen:
1. **we would suggest that those particular git hashes are somehow better than others, which is unsubstantiated**. Even though I tested compilation on my machine with those particular hashes, compilation is not what is important. `zram-generator` is a piece of system software that can only be really tested when compiled into a system package, installed on a real machine, and executed as part of a real boot. So the most important testing happens when we build an rpm/deb/… out of this and it goes through distro qa and deployment to users. And the builds in Fedora's koji and other distro systems don't use Cargo.lock, they don't use latest versions from upstream, but some semantic-version-compatible release that happens to be in the distro.
2. **when new compatible versions of dependencies with bugfixes are released, we'd still direct users to the older versions**. This is not a project which has daily commits, it can go months without any activity, which I think is totally fine, but it would mean that we pointlessly stick to those outdated versions until some unrelated commits happen. In fact, as long as rust remains mostly backwards compatible, it is likely that this project will compile and work just fine for years into the future. We certainly don't want to say that the version that happened to be the latest this Friday is the one to use two years hence.

In general, I think the recommendations in the Cargo docs stem from the culture in languages like nodejs where people are too blasé to declare and use versions and build a giant pile out of semi-random versions. I don't have any desire to participate in that.

If BuildStream wants to commit to some specific snapshot of the dependency versions and cache them, I think this is totally OK. This is to a large extent what Fedora and other distros do. But those specific versions are and should remain a downstream thing.

**Comment by AdrianVovk** [comment]
@keszybz that's fair enough. I'll look into somehow calling `cargo update` and then triggering Buildstream's existing logic. Thank you
