### ISSUE TITLE
RFE: should set priority

### ISSUE THREAD

**Issue by cmurf** [systemd/zram-generator#8]
The generator should set a priority, otherwise in the case of more than one swap (conventional and zram), it's ambiguous which one is used first, since it's kernel assigned.

```
$ swapon
NAME       TYPE      SIZE USED PRIO
/dev/sda6  partition   8G   0B   -2
/dev/zram0 partition 7.7G   0B   -3
```
Priority can be set to 0 - 32767. I think zram-generator should default to something decently high like 30000. I'm not opposed to it being configurable.

**Comment by ignatenkobrain** [comment]
This is now fixed in master. Do you think it would be worth to make it configurable?

**Comment by cmurf** [comment]
I can't think of a reason to make it configurable.

**Comment by ignatenkobrain** [comment]
@cmurf great!

**Comment by allanlaal** [comment]
please make this configurable

use case: lots of other swaps also in use and priotized in fstab

**Comment by cmurf** [comment]
> use case: lots of other swaps also in use and priotized in fstab

Ok? But the /dev/zram0 device has a priority of 100. You can prioritize the other swaps in relation to this, and each other, by just explicitly setting their priority higher or lower than 100.

Also, while I don't think it's bad to combine zram and disk based swaps, it's probably less consistent and predictable performance wise. Your workload might be better off with zram-based swap disabled, and use zswap based compressed caching instead. This will use an LRU algorithm to more effectively use the cache.

The main use case I imagine for mixed swap types is zram-based for most paging. And disk-based for hibernation. If it turns out quite a lot of stale and seldom used pages end up in zram-based swap, it's probably a less effective method of swap because it's just consuming memory with no benefit. Where other methods at least 100% evict those stale pages to disk.

**Comment by oyvindsaether** [comment]
Found this bug after looking into why zswap ain't used when it is created with zram-generator. I have three existing swaps with priorities 1000, 2000 and 3000. The silly 100 priority zram-generator defaults to ensures that those aren't used. The priority could and should be configurable, and it should in any case be documented on the manual page.

Since the maximum priority of a swap is 32767 and zram-generator is probably what you'd want to be used first, a default of 32000 instead of 100 would make more sense. However, it would be best if it was configurable.

I guess I could change existing priorities to 10, 20 and 30 but I've already decided on the simpler "systemctl mask swap-create@.service" and a short script that creates a sane zram swap for now.

**Comment by polarathene** [comment]
> I have three existing swaps with priorities 1000, 2000 and 3000. The silly 100 priority zram-generator defaults to ensures that those aren't used.

Your other swaps are configured priorities by yourself, you could just as easily set those to 10, 20, 30 as you later mention, or whatever values under 100. There isn't much reason to need priorities such as 30,000 when you can have a more sensible scale of 0-100.

You only raise a complaint about it because you opted to use 4 figure value priorities based on this range available to you when configuring priority for those other swap devices. But there is no valid reason for needing them that high. The range of 0-32767 fits into 2^15 bits, I assume the other bit is used for negative range. They could have instead gone with 8-bits for 0-255 (or -127-127), that's presumably too small for some setups so adding another byte addresses that. For practical/pragmatic purposes, you can just consider a 0-100 range. Thus 100 as highest priority is still valid.

> The priority could and should be configurable, and it should in any case be documented on the manual page.

I'm not fussed about it being configurable, but I agree that it should be documented. On systems with over 100 swap devices, zram is probably not appropriate anyhow.

> I guess I could change existing priorities to 10, 20 and 30 but I've already decided on the simpler "systemctl mask swap-create@.service" and a short script that creates a sane zram swap for now.

You could just override the priority yourself with a drop-in unit? Priority for writing the systemd unit is hard-coded here:

https://github.com/systemd/zram-generator/blob/81ef18f53a3f0efa7d30c38492a0e58a8eedfba6/src/generator.rs#L116

I'm not exactly sure when that is triggered. As the installed service generator `swap-create@` only seems to call `zram-generator` with `--setup-device` (creates the zram device and appears in `zramctl` but not `swapon`?) and `--reset-device` (removes the device, no longer visible in `zramctl`).

`zram-generator <directory>` seems to provide a location to store the `dev-zram0.swap` files that `generator.rs` snippet above is creating, and there is a directory `swap.target.wants` which includes a symlink to the `dev-zram0.swap` file and any others if configured (these map to the names in the config file like the names after the `@` in the `swap-create@zram0.service` generated services, if that's the correct term, it just uses that value as `%i` afaik to pass to `zram-generator`). I'm not sure how to manually have it become a swap device listed under `swapon`, I assume that's unrelated to this project and something else recognizes it when triggered.

Anyway, once you're setup as you are by default on Fedora with `zram-generator`, you can override those generated `.swap` files individually by using `systemctl edit dev-zram0.swap`, it'll bring up a text editor and you want to type the following:

```
[Swap]
Priority=12345
```

Save that and restart the service for that zram device, `systemctl restart swap-create@zram0.service` seems to work. `swapon` **will now report the changed priority!** You should only have to do that the one time and it should persist with that zram device. I'm not super experienced with systemd, other than restarting the system I think you have to explicitly restart each individual zram service as mentioned above (not that you'd have more than one I guess).

---

Took me a little while to figure the above out, the current documentation for the project (and the code itself when I tried to navigate what was going on) was lacking a bit. I had a much easier time when using Fedora with it already setup, but installing from source and getting it running wasn't straight-forward for a user like me.

Here's the commands I used on an Ubuntu 20.10 VPS instance:

```
apt-get update && apt install build-essential pkg-config ronn
curl https://sh.rustup.rs -sSf | sh -s -- -y
source $HOME/.cargo/env
git clone https://github.com/systemd/zram-generator
cd zram-generator && make install
cp zram-generator.conf.example /etc/systemd/zram-generator.conf
systemctl daemon-reload
```

That installs required dependencies, grabs the project, installs it and makes sure there is a config to run with.

**Comment by keszybz** [comment]
I think it's easy to enough to make this configurable. I think that's better than having people come up with custom solutions.

**Comment by polarathene** [comment]
> I think that's better than having people come up with custom solutions.

Not really sure how it's much of a custom solution? It's a systemd service, using drop-in to override the priority seems perfectly valid, albeit a bit more friction than having a supported setting in the conf file.
